version: '3'
services:
  cookiecloud:
    image: ghcr.io/nichuanfang/cookiecloud:latest
    container_name: cookiecloud-app
    restart: always
    environment:
      WEBHOOK_URL: https://webhook.chuanfang.org/cookiecloud
    volumes:
      - ./data:/data/api/data
    ports:
      - "8088:8088"